language: c++
sudo: true # for FUSE
dist: trusty

# cache:
#     directories:
#         - Qt

script:
    - make HelloWorld
    - rm -rf ./appdir
    - mkdir ./appdir
    - cp subsurface-icon.png HelloWorld HelloWorld.desktop ./appdir
    - wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
    - chmod a+x appimagetool-x86_64.AppImage
    - ./appimagetool-x86_64.AppImage ./appdir
    - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq

after_success:
    - ls -lh HelloWorld*.AppImage
    - echo "Travis claims our branch is" $TRAVIS_BRANCH
    - if [ ! -z $TRAVIS_BRANCH ] && [ "$TRAVIS_BRANCH" != "master" ] ; then export UPLOADTOOL_SUFFIX=$TRAVIS_BRANCH ; fi
    - wget -c https://github.com/dirkhh/uploadtool/raw/master/upload.sh
    - bash -x ./upload.sh HelloWorld*.AppImage
    - RELEASE_NAME="continuous"
    - RELEASE_TITLE="Release for continuous"
    - BODY="Testin 1-2-3"
    - release_id=${curl https://api.github.com/repos/Subsurface-divelog/subsurface/releases/tags/${RELEASE_NAME} | grep id: |grep "\"id\":" | head -n 1 | tr -s " " | cut -f 3 -d" " | cut -f 1 -d ",")
    - release_infos=$(curl -H "Authorization: token ${GITHUB_TOKEN}" --request PATCH \
       --data '{"tag_name": "'"$RELEASE_NAME"'","name": "'"$RELEASE_TITLE"'","body": "'"$BODY"'"}' "https://api.github.com/repos/Subsurface-divelog/subsurface/releases/${release_id}")


branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
