language: c++
sudo: true # for FUSE
dist: trusty

# cache:
#     directories:
#         - Qt

script:
    - make HelloWorld
    - rm -rf ./appdir
    - mkdir ./appdir
    - cp subsurface-icon.png HelloWorld HelloWorld.desktop ./appdir
    - wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
    - chmod a+x appimagetool-x86_64.AppImage
    - ./appimagetool-x86_64.AppImage ./appdir
    - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq

after_success:
    - ls -lh HelloWorld*.AppImage
    - echo "Travis claims our branch is" $TRAVIS_BRANCH
    - if [ ! -z $TRAVIS_BRANCH ] && [ "$TRAVIS_BRANCH" != "master" ] ; then export UPLOADTOOL_SUFFIX=$TRAVIS_BRANCH ; fi
    - wget -c https://github.com/dirkhh/uploadtool/raw/master/upload.sh
    - bash -x ./upload.sh HelloWorld*.AppImage HelloWorld
    - ls -l ${TRAVIS_BUILD_DIR}


branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
